# Generated by Django 5.1.6 on 2025-04-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(default='', upload_to='flower_image'),
        ),
    ]
